In [1]:
import  pandas  as pd
import numpy as np
df1=pd.read_excel('附件1 近5年402家供应商的相关数据.xlsx',sheet_name='企业的订货量（m³）')#可以通过sheet_name来指定读取的表单
data1=df1.head()#默认读取前5行的数据
print("获取到所有的值:\n{0}".format(data1))#格式化输出
df2=pd.read_excel('附件1 近5年402家供应商的相关数据.xlsx',sheet_name='供应商的供货量（m³）')#可以通过sheet_name来指定读取的表单
data2=df2.head()#默认读取前5行的数据
print("获取到所有的值:\n{0}".format(data2))#格式化输出

获取到所有的值:
  供应商ID 材料分类  W001  W002  W003  W004  W005  W006  W007  W008  ...  W231  W232  \
0  S001    B     0     0     0    43     0     0     0     0  ...     1     0
1  S002    A     1     1     0     1     0     0     0     0  ...     0     0
2  S003    C     7     1     0     0     0     1     4    50  ...    10     3
3  S004    B     0     1     1   100     0    85     0     0  ...     1     0
4  S005    A    30    60    60    60    70    70    60    70  ...    80    70

   W233  W234  W235  W236  W237  W238  W239  W240
0     0     1     0     1     0     0     0     0
1     1     0     0     0     1     1     0     1
2    50    20    20     7    10     9    20    10
3     1     0     0     0     0     1     0     0
4    70    70    70    70    70    70    70    80

[5 rows x 242 columns]
获取到所有的值:
  供应商ID 材料分类  W001  W002  W003  W004  W005  W006  W007  W008  ...  W231  W232  \
0  S001    B     0     0     0     0     0     0     0     0  ...     0     0
1  S002    A     1     0     0     1     0     0     0     0  ...     0     0
2  S003    C     8     1     0     0     0     1     5    58  ...     9     4
3  S004    B     0     0     0     0     0     0     0     0  ...     0     0
4  S005    A    37    62    60    65    76    76    65    71  ...    84    78

   W233  W234  W235  W236  W237  W238  W239  W240
0     0     1     0     2     0     0     0     0
1     0     0     0     0     0     0     0     1
2    54    20    20     8    18    10    22    11
3     0     0     0     0     0     0     0     0
4    77    79    78    75    74    74    76    81

[5 rows x 242 columns]

In [2]:
#求相关系数
df2_new_abc=df2.copy()#记录材料
df1.drop('供应商ID',axis=1,inplace=True)
df1.drop('材料分类',axis=1,inplace=True)
df2.drop('供应商ID',axis=1,inplace=True)
df2.drop('材料分类',axis=1,inplace=True)
print(df1)
print(df2)

     W001  W002  W003  W004  W005  W006  W007  W008  W009  W010  ...  W231  \
0       0     0     0    43     0     0     0     0     1     0  ...     1
1       1     1     0     1     0     0     0     0     0     1  ...     0
2       7     1     0     0     0     1     4    50   130   170  ...    10
3       0     1     1   100     0    85     0     0     0     0  ...     1
4      30    60    60    60    70    70    60    70    70    80  ...    80
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...
397     0     1     0    70     0     0     0     0     0     0  ...     0
398     0     0     1     0     0     0     0     1     0     1  ...     0
399     0     1     0    60     0     1     0     1     3     2  ...     0
400     0     0     0     0     0     0     6     1     0     1  ...     0
401     0     0     0     0     1     0     0     0     0     0  ...     0

     W232  W233  W234  W235  W236  W237  W238  W239  W240
0       0     0     1     0     1     0     0     0     0
1       0     1     0     0     0     1     1     0     1
2       3    50    20    20     7    10     9    20    10
3       0     1     0     0     0     0     1     0     0
4      70    70    70    70    70    70    70    70    80
..    ...   ...   ...   ...   ...   ...   ...   ...   ...
397     0     0     0     0     0     1     0     0     0
398     0     1     0     0     0     0     0     1     0
399     0     0     0     1     0     1     0     0     0
400     0     1     1     0     0     0     0     1     1
401     0     0     0     1     1     0     1     0     0

[402 rows x 240 columns]
     W001  W002  W003  W004  W005  W006  W007  W008  W009  W010  ...  W231  \
0       0     0     0     0     0     0     0     0     0     0  ...     0
1       1     0     0     1     0     0     0     0     0     2  ...     0
2       8     1     0     0     0     1     5    58   110   173  ...     9
3       0     0     0     0     0     0     0     0     0     0  ...     0
4      37    62    60    65    76    76    65    71    72    80  ...    84
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...
397     0     0     0     0     0     0     0     0     0     0  ...     0
398     0     0     0     0     0     0     0     0     0     0  ...     0
399     0     0     0     0     0     0     0     0     4     3  ...     0
400     0     0     0     0     0     0     0     0     0     0  ...     0
401     0     0     0     0     0     0     0     0     0     0  ...     0

     W232  W233  W234  W235  W236  W237  W238  W239  W240
0       0     0     1     0     2     0     0     0     0
1       0     0     0     0     0     0     0     0     1
2       4    54    20    20     8    18    10    22    11
3       0     0     0     0     0     0     0     0     0
4      78    77    79    78    75    74    74    76    81
..    ...   ...   ...   ...   ...   ...   ...   ...   ...
397     0     0     0     0     0     0     0     0     0
398     0     0     0     0     0     0     0     0     0
399     0     0     0     0     0     0     0     0     0
400     0     0     0     0     0     0     0     0     0
401     0     0     0     0     0     0     0     0     0

[402 rows x 240 columns]

In [3]:
corr=[]#相关系数
for i in range(0,402):
    corr.append(df1.loc[i].corr(df2.loc[i],method='kendall'))
print(corr)

[0.4784139719095534, 0.8070084319844756, 0.9355519917253328, 0.5318495512157729, 0.9468074914194625, 0.46785120069800673, 0.6541838882353583, 0.49212911538515025, 0.4651229983992355, 0.5808370900804624, 0.8479546370535639, 0.39072966507579004, 0.8159234019455173, 0.7598843396033989, 0.4740693883530197, 0.8750795822971691, 0.6111047176385733, 0.6250479677653026, 0.45508502421613783, 0.571340459561897, 0.7883662422052077, 0.48939551105398704, 0.7407018581703374, 0.725826528518372, 0.9268504794860776, 0.8997202659596675, 0.7881056861463164, 0.63327369414598, 0.5649708251263186, 0.9782065389339064, 0.8956634950745839, 0.6704420900180043, 0.9403711188618582, 0.41259154433738443, 0.6927021821105265, 0.9393498118586697, 0.9503017171943138, 0.4962318147074863, 0.8085219698286575, 0.8495200580946358, 0.6538337608856615, 0.6527973321991297, 0.49617430668263707, 0.9035125697747294, 0.4326598622457956, 0.7523237625514139, 0.5377473052089314, 0.699179080663513, 0.6484008577646729, 0.9417339324224312, 0.45649047023251815, 0.7302275178342456, 0.9938316344914562, 0.859716053240738, 0.7513892149585429, 0.6090710932592932, 0.5883054372573694, 0.4775654351974794, 0.6081193029831873, 0.6460714809819758, 0.6251030054306312, 0.5492434436113459, 0.47482909334462303, 0.8968141757985374, 0.8129098276723115, 0.9074301179460491, 0.8430727687993829, 0.4679265502344313, 0.7735488026044259, 0.8374687950614194, 0.4365672376739868, 0.6169347712015866, 0.8477217514256458, 0.7838255559017785, 0.9199518433177504, 0.7437897838251485, 0.4384121755424937, 0.9370409995132429, 0.6473850801048312, 0.8835659072023218, 0.8399332114055715, 0.58990294406949, 0.6349116539970028, 0.4909457212091273, 0.6057549404072552, 0.8717465123810542, 0.828501716539176, 0.8577783557242376, 0.7390334770617561, 0.8109403997437875, 0.7261680190006619, 0.9461222394258003, 0.43586947308361085, 0.6521011876551366, 0.4182875910883989, 0.6519656363993257, 0.5369731976976677, 0.7739302415233077, 0.7541836537758546, 0.4295317025897044, 0.5532123546892537, 0.8331980441906998, 0.4619890418458456, 0.5693609643774443, 0.6734350954325251, 0.9616905227477612, 0.6432100089737928, 0.8967753960002302, 0.5512946524948601, 0.8497008275359303, 0.618900047588889, 0.5560304943996742, 0.9408321700196158, 0.8805773999246793, 0.8560724373992371, 0.7759888774638017, 0.7273175327483083, 0.5544675435877993, 0.4205342756333005, 0.6952765775048904, 0.6746658580115256, 0.810897207509287, 0.6018846585126121, 0.6722731118924143, 0.5127810884617413, 0.8992768688506669, 0.6176037769862224, 0.8175922618474621, 0.8184483103474764, 0.5119227580521789, 0.9141575896346286, 0.7326525896415418, 0.9208236400201948, 0.5584704272014225, 0.496400546040901, 0.6318090631731174, 0.4075516362386999, 0.8679373438950804, 0.8818798340728145, 0.9136041997679226, 0.9332424141275251, 0.550213563204017, 0.9064295051974522, 0.3886492027495354, 0.573097937123982, 0.6141443716839866, 0.6207315065987159, 0.5520533305113793, 0.9305497929336995, 0.8114107581389651, 0.9268949626038803, 0.8878070240083996, 0.419748935038461, 0.8404677826480326, 0.5422557931166572, 0.5550896690342524, 0.8545591620567338, 0.5632468414157629, 0.7346895022984112, 0.46902355017033454, 0.4584871036475135, 0.35614667726262267, 0.7166115555955272, 0.49774093290554644, 0.6865628340906853, 0.5251588274260968, 0.6216950329805127, 0.4760638322468815, 0.9621511603357553, 0.7514753995373965, 0.6593877234835833, 0.9062694945072566, 0.6104098831559638, 0.9674641438023124, 0.9460118196491917, 0.7210121306026874, 0.49592102928219206, 0.9952560660391507, 0.3956720479754525, 0.9176472140582611, 0.5077690656952217, 0.7276121048937296, 0.35644083141696714, 0.6807691243551107, 0.5476871186734947, 0.9020426026293136, 0.5491852806706268, 0.9312678360150031, 0.9103939931626546, 0.38819122342343076, 0.8632190859079902, 0.4361459665614539, 0.9109658297734649, 0.9154719390138, 0.6041739302164739, 0.6216049912664757, 0.9189911453250241, 0.4987495730693863, 0.7459180137730949, 0.5815904544107823, 0.6962238207083327, 0.9261744210561222, 0.895185814084591, 0.4450959424305633, 0.6175656997390474, 0.9603203810624935, 0.6402508539077097, 0.8016207235566123, 0.685090136490711, 0.7818266078630098, 0.89737949042298, 0.39760995608888194, 0.8196443959671378, 0.6553542100114229, 0.39455062610770075, 0.8764593563253176, 0.6866009637211964, 0.9074877168994328, 0.8033773159564448, 0.6339959698911738, 0.9715128973736531, 0.5767150072664866, 0.6512372693021821, 0.8103406890635286, 0.9297020956151636, 0.7443775725854084, 0.8618097146664551, 0.4833902186953575, 0.9564971160097882, 0.8208303535461126, 0.4045280330230968, 0.7845715341859064, 0.7828852801272234, 0.5609597209099471, 0.8821602322815787, 0.7892428258235877, 0.9503807983225572, 0.22248131180324227, 0.971483627422011, 0.3199239190332152, 0.4481567915896209, 0.6302224511313295, 0.5447198065605842, 0.8912420535542088, 0.7493622004901462, 0.4463449891235357, 0.919107193797603, 0.5387955926370293, 0.675497769146122, 0.7908947973478442, 0.3409237366554529, 0.6007757262839705, 0.9561087545933047, 0.7553766088807621, 0.6912087990521006, 0.9270550182943784, 0.48543468497967485, 0.8966488320614744, 0.7164526594123489, 0.7618655768696184, 0.6414057653666889, 0.43639455352441375, 0.8637176445672685, 0.7024486253616934, 0.8100330330093457, 0.4380113760053183, 0.7743263815122109, 0.9388953393309899, 0.721926224132589, 0.9341829547067577, 0.8604646469801309, 0.8708172345408298, 0.9274714544201225, 0.7850607839624718, 0.9686814981970885, 0.4799914930986168, 0.38108005673839107, 0.548007493656368, 0.8310622364554769, 0.6930488237130215, 0.5267303521793542, 0.9939486934992703, 0.4516149173578977, 0.9866387230308117, 0.37875037487295565, 0.8461825480512235, 0.29190825841042994, 0.6211712222109078, 0.4784096756133927, 0.45047918989940505, 0.9072064549851502, 0.8358745704719579, 0.3137028936404465, 0.8028749600597075, 0.7313218274858716, 0.7870163787481685, 0.4078213240062468, 0.8710264201411106, 0.5167473639120223, 0.8490502027518742, 0.8667769300402358, 0.48988666295934097, 0.8011122225266258, 0.8604260981233682, 0.8823141625209242, 0.9699102962381962, 0.9410888677730951, 0.9148125682823894, 0.800790498686699, 0.9017973377413644, 0.5881409506253048, 0.705119002357448, 0.7030119389291429, 0.8548752121318701, 0.6641638169062726, 0.7937637783540071, 0.43721639912974686, 0.9052261735575067, 0.6152630309199859, 0.5400191031376104, 0.41515297704907084, 0.6477236923403237, 0.651463755972195, 0.9407013340299475, 0.6482519732224625, 0.6612005634620509, 0.7505527506734188, 0.34037137886975494, 0.9563811016177417, 0.9317182974781772, 0.7756108806224933, 0.9298668887804278, 0.7678113096742986, 0.3796747283237833, 0.5421902795016743, 0.800740875014314, 0.8391243309264674, 0.9586511347839138, 0.7185448777778275, 0.9552005671386445, 0.6484661342409883, 0.9831526011297114, 0.3904965638626185, 0.4459825256596366, 0.64033851828438, 0.7705441223257139, 0.6157108529906545, 0.9175357550039931, 0.7926384125416089, 0.45849722806392335, 0.9559400849459114, 0.9544797213769856, 0.8896432753691155, 0.5445969178342243, 0.47962444373460744, 0.9696419853017726, 0.87313099835839, 0.8132454973219232, 0.8025451882780044, 0.8515937100564965, 0.9460216461963835, 0.9815959416539227, 0.6268095843537754, 0.8783811811428981, 0.9314254438968039, 0.8653575734186022, 0.8856507381533085, 0.6545556818211845, 0.5647839743128428, 0.6893100766809072, 0.5555792048863849, 0.4975146059102952, 0.44487069862185197, 0.9384110347373403, 0.44842580648030583, 0.8835546455719674, 0.7126559040065528, 0.598666401164858, 0.9820749810494621, 0.6641472593997798, 0.9218889264582726, 0.6219063329465342, 0.8863733344214136, 0.6394326693654263, 0.49741136040874634, 0.8546556861097144, 0.3726606512106271, 0.9279669769573805, 0.7862791458932318, 0.5116490909976487, 0.5593812433924398, 0.9261512801007238, 0.1866130242164977, 0.40060790134315066, 0.9047230998343383, 0.45659161019270605, 0.9193539024489339, 0.6197590759405966, 0.6857032076838304, 0.39180381640244505, 0.6307571341974181, 0.31483464794861604]

In [4]:
from numpy import *
df2_new=df2.copy()
df2_new['变异系数']=df2.apply(lambda x:x.std(),axis =1)/df2.apply(lambda x:x.mean(),axis =1)
df2_new['变异系数']=df2_new['变异系数']/sqrt(240)
# annualVolatility = std(logreturns) / mean(logreturns)
# annualVolatility = annualVolatility / sqrt(1/252)
df2_new["总和"] =df2.apply(lambda x:x.sum(),axis =1)
df2_new["均值"] =df2.apply(lambda x:x.mean(),axis =1)
df2_new["标准差"] =df2.apply(lambda x:x.mean(),axis =1)
df2_new['零值率']=(df2 == 0).sum(axis=1)
df2_new

,W001,W002,W003,W004,W005,W006,W007,W008,W009,W010,...,W236,W237,W238,W239,W240,变异系数,总和,均值,标准差,零值率
0,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0.230465,49,0.204167,0.204167,215
1,1,0,0,1,0,0,0,0,0,2,...,0,0,0,0,1,0.282961,273,1.137500,1.137500,169
2,8,1,0,0,0,1,5,58,110,173,...,8,18,10,22,11,0.089981,13138,54.741667,54.741667,49
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.208272,64,0.266667,0.266667,207
4,37,62,60,65,76,76,65,71,72,80,...,75,74,74,76,81,0.081264,6912,28.800000,28.800000,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.289188,41,0.170833,0.170833,224
398,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.201834,65,0.270833,0.270833,210
399,0,0,0,0,0,0,0,0,4,3,...,0,0,0,0,0,0.432518,53,0.220833,0.220833,227
400,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.223997,67,0.279167,0.279167,211
401,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.596391,35,0.145833,0.145833,232

In [5]:
df2_new02=df2.T
df2_new02

,0,1,2,3,4,5,6,7,8,9,...,392,393,394,395,396,397,398,399,400,401
W001,0,1,8,0,37,0,9,0,0,0,...,0,0,945,0,0,0,0,0,0,0
W002,0,0,1,0,62,0,94,0,0,0,...,0,0,0,0,1,0,0,0,0,0
W003,0,0,0,0,60,0,37,0,0,0,...,0,0,0,0,0,0,0,0,0,0
W004,0,1,0,0,65,0,102,0,0,0,...,0,0,0,0,0,0,0,0,0,0
W005,0,0,0,0,76,0,25,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
W236,2,0,8,0,75,0,19,0,0,0,...,0,0,0,0,1,0,0,0,0,0
W237,0,0,18,0,74,0,17,0,0,0,...,0,0,0,0,0,0,0,0,0,0
W238,0,0,10,0,74,0,19,0,0,0,...,0,0,0,0,0,0,0,0,0,0
W239,0,0,22,0,76,0,21,0,0,0,...,0,0,0,0,0,0,0,0,0,0
W240,0,1,11,0,81,0,17,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
def regularit(df2_new02):
    df2_new03 = pd.DataFrame(index=df2_new02.index)
    columns = df2_new02.columns.tolist()
    for c in columns:
        d = df2_new02[c]
        MAX = d.max()
        MIN = d.min()
        df2_new03[c] = ((d - MIN) / (MAX - MIN)).tolist()
    return df2_new03
df2_new03=regularit(df2_new02)
#df2_new03=df2_new03.T
df2_new03

,0,1,2,3,4,5,6,7,8,9,...,392,393,394,395,396,397,398,399,400,401
W001,0.000000,0.014925,0.020672,0.0,0.289062,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.123352,0.0,0.0,0.0,0.0,0.0,0.0,0.0
W002,0.000000,0.000000,0.002584,0.0,0.484375,0.0,0.582192,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0
W003,0.000000,0.000000,0.000000,0.0,0.468750,0.0,0.191781,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
W004,0.000000,0.014925,0.000000,0.0,0.507812,0.0,0.636986,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
W005,0.000000,0.000000,0.000000,0.0,0.593750,0.0,0.109589,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
W236,0.333333,0.000000,0.020672,0.0,0.585938,0.0,0.068493,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0
W237,0.000000,0.000000,0.046512,0.0,0.578125,0.0,0.054795,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
W238,0.000000,0.000000,0.025840,0.0,0.578125,0.0,0.068493,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
W239,0.000000,0.000000,0.056848,0.0,0.593750,0.0,0.082192,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
W240,0.000000,0.014925,0.028424,0.0,0.632812,0.0,0.054795,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
df2_new03[1]

W001    0.014925
W002    0.000000
W003    0.000000
W004    0.014925
W005    0.000000
          ...
W236    0.000000
W237    0.000000
W238    0.000000
W239    0.000000
W240    0.014925
Name: 1, Length: 240, dtype: float64

In [8]:
df2_new['波动率']=''
df2_new

,W001,W002,W003,W004,W005,W006,W007,W008,W009,W010,...,W237,W238,W239,W240,变异系数,总和,均值,标准差,零值率,波动率
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.230465,49,0.204167,0.204167,215,
1,1,0,0,1,0,0,0,0,0,2,...,0,0,0,1,0.282961,273,1.137500,1.137500,169,
2,8,1,0,0,0,1,5,58,110,173,...,18,10,22,11,0.089981,13138,54.741667,54.741667,49,
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.208272,64,0.266667,0.266667,207,
4,37,62,60,65,76,76,65,71,72,80,...,74,74,76,81,0.081264,6912,28.800000,28.800000,133,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.289188,41,0.170833,0.170833,224,
398,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.201834,65,0.270833,0.270833,210,
399,0,0,0,0,0,0,0,0,4,3,...,0,0,0,0,0.432518,53,0.220833,0.220833,227,
400,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.223997,67,0.279167,0.279167,211,
401,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.596391,35,0.145833,0.145833,232,

In [9]:
np.quantile(df2_new03[1], 0.9,axis=0)
df2_new.loc[1,'波动率'] = 1
#df2_new['波动率'][1]='1'
df2_new
#print((np.quantile(df2_new03[1], 0.9,axis=0) - np.quantile(df2_new03[1], 0.1, axis=0) + 1) /  (np.quantile(df2_new03[1],0.1, axis=0) + 1))

,W001,W002,W003,W004,W005,W006,W007,W008,W009,W010,...,W237,W238,W239,W240,变异系数,总和,均值,标准差,零值率,波动率
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.230465,49,0.204167,0.204167,215,
1,1,0,0,1,0,0,0,0,0,2,...,0,0,0,1,0.282961,273,1.137500,1.137500,169,1
2,8,1,0,0,0,1,5,58,110,173,...,18,10,22,11,0.089981,13138,54.741667,54.741667,49,
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.208272,64,0.266667,0.266667,207,
4,37,62,60,65,76,76,65,71,72,80,...,74,74,76,81,0.081264,6912,28.800000,28.800000,133,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.289188,41,0.170833,0.170833,224,
398,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.201834,65,0.270833,0.270833,210,
399,0,0,0,0,0,0,0,0,4,3,...,0,0,0,0,0.432518,53,0.220833,0.220833,227,
400,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.223997,67,0.279167,0.279167,211,
401,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.596391,35,0.145833,0.145833,232,

In [10]:
for i in range(0,402):
    df2_new.loc[i,'波动率'] =np.quantile(df2_new03[i], 0.9,axis=0) - np.quantile(df2_new03[i], 0.1, axis=0)
#df2_new['波动率'].apply(lambda x:(np.quantile(df2_new03[x], 0.9,axis=0) - np.quantile(df2_new03[x], 0.1, axis=0) + 1) /  (np.quantile(df2_new03[x],0.1, axis=0) + 1)
# df2_new['波动率'][1]=(np.quantile(df2_new03[1], 0.9,axis=0) - np.quantile(df2_new03[1], 0.1, axis=0) + 1) / (df2_new03[1],0.1, axis=0) + 1)
df2_new
# df.loc[(df.traj_id == id), 'quantile_lng'] = (np.quantile(df.loc[(df.traj_id == id), 'norm_lng'], 0.9,
#                                                                   axis=0) - np.quantile(
#             df.loc[(df.traj_id == id), 'norm_lng'], 0.1, axis=0) + 1) / (
#                                                                  np.quantile(df.loc[(df.traj_id == id), 'norm_lng'],
#                                                                              0.1, axis=0) + 1)

,W001,W002,W003,W004,W005,W006,W007,W008,W009,W010,...,W237,W238,W239,W240,变异系数,总和,均值,标准差,零值率,波动率
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.230465,49,0.204167,0.204167,215,0.166667
1,1,0,0,1,0,0,0,0,0,2,...,0,0,0,1,0.282961,273,1.137500,1.137500,169,0.0298507
2,8,1,0,0,0,1,5,58,110,173,...,18,10,22,11,0.089981,13138,54.741667,54.741667,49,0.449871
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.208272,64,0.266667,0.266667,207,0.125
4,37,62,60,65,76,76,65,71,72,80,...,74,74,76,81,0.081264,6912,28.800000,28.800000,133,0.610156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.289188,41,0.170833,0.170833,224,0
398,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.201834,65,0.270833,0.270833,210,0.2
399,0,0,0,0,0,0,0,0,4,3,...,0,0,0,0,0.432518,53,0.220833,0.220833,227,0
400,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.223997,67,0.279167,0.279167,211,0.125
401,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.596391,35,0.145833,0.145833,232,0

In [11]:
order_data = pd.read_excel('附件1 近5年402家供应商的相关数据.xlsx',sheet_name = 0)
provide_data = pd.read_excel('附件1 近5年402家供应商的相关数据.xlsx',sheet_name=1)
#print(order_data)
#print(provide_data)
turn = {'A':0.6,'B':0.66,'C':0.72}
t = provide_data.set_index(['供应商ID','材料分类']).T

In [12]:
sum_new=[]#换算产量后的总和
for i in t.columns[0:]:
    sum_new.append(round(((t[i].sum()/turn[i[1]])), 2))
    #print(i,t[i].sum()/turn[i[1]]) 
sum_new#一个list,存储换算后总量

[74.24,
 455.0,
 18247.22,
 96.97,
 11520.0,
 41.67,
 11580.0,
 56.94,
 46.97,
 257.58,
 118.06,
 48.33,
 61.11,
 46.67,
 46.67,
 61.67,
 230.0,
 100.0,
 165.15,
 100.0,
 133.33,
 233.33,
 2265.28,
 187.88,
 520.83,
 46.67,
 135.0,
 160.61,
 103.03,
 270.0,
 62434.85,
 98.61,
 41.67,
 41.67,
 240.0,
 187.88,
 70397.22,
 60.0,
 534.72,
 48340.91,
 98.61,
 230.0,
 65.0,
 41.67,
 46.97,
 328.33,
 100.0,
 98.48,
 63.33,
 100.0,
 48.33,
 90.0,
 128.33,
 625.76,
 36425.76,
 46.67,
 75.76,
 51.52,
 65.28,
 119.44,
 116.67,
 125.0,
 41.67,
 661.67,
 315.0,
 646.67,
 323.61,
 58.33,
 256.06,
 63.89,
 318.33,
 46.67,
 48.48,
 18126.39,
 650.0,
 522.22,
 193.94,
 14255.0,
 96.97,
 26718.06,
 74.24,
 96.67,
 46.67,
 97.22,
 63.89,
 24929.17,
 106.67,
 643.94,
 235.0,
 201.39,
 121.67,
 603.03,
 60.0,
 56.94,
 48.48,
 121.67,
 105.0,
 625.76,
 100.0,
 58.33,
 93.33,
 218.33,
 41.67,
 258.33,
 181.82,
 128.33,
 95.83,
 365075.76,
 60.0,
 591.67,
 46.97,
 186.36,
 534.72,
 18218.33,
 663.33,
 125.0,
 186.36,
 100.0,
 48.33,
 50.0,
 228.33,
 121.67,
 10748.33,
 51.52,
 74.24,
 66027.78,
 263.33,
 221.67,
 2118.06,
 100.0,
 208351.52,
 105.0,
 98.61,
 78.79,
 120.83,
 58.33,
 50.0,
 622.73,
 230093.94,
 457646.97,
 636.36,
 183.33,
 137978.33,
 46.67,
 105.0,
 533.33,
 163.64,
 98.33,
 348.61,
 3010.0,
 270136.11,
 663.33,
 265.15,
 12723.33,
 66.67,
 46.67,
 658.33,
 61.67,
 358.33,
 62.5,
 65.28,
 38.89,
 420.0,
 100.0,
 125.0,
 48.48,
 226.67,
 46.97,
 543.94,
 225.0,
 100.0,
 539.39,
 516.67,
 524.24,
 554.55,
 77.27,
 65.28,
 271.67,
 46.97,
 78.79,
 60.0,
 212.5,
 38.89,
 121.67,
 106.67,
 523.61,
 123.33,
 77.27,
 14820.0,
 72.73,
 531.82,
 41.67,
 153.03,
 140784.72,
 60.0,
 66.67,
 536.36,
 90.0,
 196.97,
 98.48,
 136648.33,
 606.06,
 60.0,
 135.0,
 100.0,
 43.06,
 213.89,
 14595.0,
 271.67,
 21797.22,
 96.67,
 43.06,
 341.67,
 78.79,
 75.76,
 643.94,
 231.67,
 21504.17,
 60.0,
 97.22,
 653.33,
 48.48,
 38.89,
 163.64,
 48.48,
 333.33,
 423.33,
 209.72,
 591478.33,
 78.79,
 43.06,
 180.3,
 271.21,
 62.5,
 286.36,
 38.89,
 546.67,
 48.48,
 597.22,
 74.24,
 38.89,
 131.67,
 105.0,
 22786.11,
 536.11,
 61.11,
 78747.22,
 104.55,
 101.52,
 58.33,
 60.0,
 66.67,
 309.72,
 268.33,
 60.0,
 622.73,
 43.06,
 627.27,
 101.52,
 278.79,
 104.55,
 38.89,
 593.06,
 48.48,
 235.0,
 10865.0,
 113.89,
 180258.33,
 351.67,
 127.78,
 343.06,
 48.48,
 15806.67,
 128.33,
 264255.0,
 78.79,
 41.67,
 103.33,
 123.61,
 192.42,
 60.0,
 282233.33,
 50.0,
 64718.06,
 58.33,
 101.52,
 100.0,
 50.0,
 66.67,
 43.06,
 13306.67,
 15266.67,
 320.0,
 26169.44,
 93.33,
 103.33,
 43.06,
 77.27,
 103.33,
 498.33,
 123.61,
 98.33,
 81.82,
 260.0,
 38.89,
 175133.33,
 130326.67,
 207572.73,
 61.67,
 615.15,
 98.48,
 128.33,
 533.33,
 2319.44,
 48.48,
 104.55,
 48.33,
 576.67,
 100.0,
 58.33,
 50.0,
 103.03,
 48.33,
 642.42,
 101.39,
 113.89,
 53.03,
 50.0,
 260863.33,
 207048.48,
 97.22,
 508.33,
 269.7,
 205.56,
 75.76,
 240.0,
 60.0,
 45619.7,
 61.11,
 259736.36,
 105.0,
 311.11,
 38.89,
 81.82,
 120.83,
 35212.12,
 113.89,
 154035.0,
 58.33,
 65.0,
 61.11,
 148385.0,
 103.03,
 95.0,
 43.06,
 180981.94,
 305.56,
 51.52,
 119.44,
 613.64,
 455666.67,
 126.39,
 93.33,
 43580.3,
 57820.83,
 74.24,
 39901.52,
 119.44,
 202.78,
 96.67,
 81.82,
 48.33,
 50.0,
 68366.67,
 169.7,
 542.42,
 98.61,
 74.24,
 345.83,
 118.06,
 335.0,
 38.89,
 204.17,
 123.61,
 80.3,
 180.3,
 50.0,
 172.73,
 104.55,
 100.0,
 97.22,
 624.24,
 50.0,
 240.0,
 126405.0,
 63.33,
 78.79,
 56.94,
 98.48,
 80.3,
 101.52,
 53.03]

In [13]:
df2_new['总和_new']=sum_new
df2_new

,W001,W002,W003,W004,W005,W006,W007,W008,W009,W010,...,W238,W239,W240,变异系数,总和,均值,标准差,零值率,波动率,总和_new
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.230465,49,0.204167,0.204167,215,0.166667,74.24
1,1,0,0,1,0,0,0,0,0,2,...,0,0,1,0.282961,273,1.137500,1.137500,169,0.0298507,455.00
2,8,1,0,0,0,1,5,58,110,173,...,10,22,11,0.089981,13138,54.741667,54.741667,49,0.449871,18247.22
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.208272,64,0.266667,0.266667,207,0.125,96.97
4,37,62,60,65,76,76,65,71,72,80,...,74,76,81,0.081264,6912,28.800000,28.800000,133,0.610156,11520.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.289188,41,0.170833,0.170833,224,0,56.94
398,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.201834,65,0.270833,0.270833,210,0.2,98.48
399,0,0,0,0,0,0,0,0,4,3,...,0,0,0,0.432518,53,0.220833,0.220833,227,0,80.30
400,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.223997,67,0.279167,0.279167,211,0.125,101.52
401,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.596391,35,0.145833,0.145833,232,0,53.03

In [14]:
df2_new['均值_new']=df2_new['总和_new']/(240-df2_new['零值率'])
df2_new['相关系数']=corr
df2_new

,W001,W002,W003,W004,W005,W006,W007,W008,W009,W010,...,W240,变异系数,总和,均值,标准差,零值率,波动率,总和_new,均值_new,相关系数
0,0,0,0,0,0,0,0,0,0,0,...,0,0.230465,49,0.204167,0.204167,215,0.166667,74.24,2.969600,0.478414
1,1,0,0,1,0,0,0,0,0,2,...,1,0.282961,273,1.137500,1.137500,169,0.0298507,455.00,6.408451,0.807008
2,8,1,0,0,0,1,5,58,110,173,...,11,0.089981,13138,54.741667,54.741667,49,0.449871,18247.22,95.535183,0.935552
3,0,0,0,0,0,0,0,0,0,0,...,0,0.208272,64,0.266667,0.266667,207,0.125,96.97,2.938485,0.531850
4,37,62,60,65,76,76,65,71,72,80,...,81,0.081264,6912,28.800000,28.800000,133,0.610156,11520.00,107.663551,0.946807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,0,0,0,0,0,0,0,0,0,0,...,0,0.289188,41,0.170833,0.170833,224,0,56.94,3.558750,0.619759
398,0,0,0,0,0,0,0,0,0,0,...,0,0.201834,65,0.270833,0.270833,210,0.2,98.48,3.282667,0.685703
399,0,0,0,0,0,0,0,0,4,3,...,0,0.432518,53,0.220833,0.220833,227,0,80.30,6.176923,0.391804
400,0,0,0,0,0,0,0,0,0,0,...,0,0.223997,67,0.279167,0.279167,211,0.125,101.52,3.500690,0.630757
401,0,0,0,0,0,0,0,0,0,0,...,0,0.596391,35,0.145833,0.145833,232,0,53.03,6.628750,0.314835

In [15]:
df_final=df2_new[['相关系数','变异系数','波动率','总和_new','均值_new','零值率']]
df_final

         相关系数      变异系数        波动率    总和_new      均值_new  零值率
0    0.478414  0.230465   0.166667     74.24    2.969600  215
1    0.807008  0.282961  0.0298507    455.00    6.408451  169
2    0.935552  0.089981   0.449871  18247.22   95.535183   49
3    0.531850  0.208272      0.125     96.97    2.938485  207
4    0.946807  0.081264   0.610156  11520.00  107.663551  133
..        ...       ...        ...       ...         ...  ...
397  0.619759  0.289188          0     56.94    3.558750  224
398  0.685703  0.201834        0.2     98.48    3.282667  210
399  0.391804  0.432518          0     80.30    6.176923  227
400  0.630757  0.223997      0.125    101.52    3.500690  211
401  0.314835  0.596391          0     53.03    6.628750  232

[402 rows x 6 columns]

In [16]:
df_zero=pd.read_excel('连续为0的数量.xlsx')#可以通过sheet_name来指定读取的表单
list_0=[]
list_0=df_zero['连续为0量'].tolist()
list_0

[43,
 28,
 5,
 48,
 74,
 44,
 0,
 65,
 53,
 69,
 36,
 66,
 53,
 44,
 99,
 44,
 65,
 31,
 56,
 31,
 31,
 103,
 3,
 41,
 3,
 53,
 36,
 23,
 31,
 65,
 0,
 31,
 53,
 110,
 15,
 40,
 10,
 64,
 60,
 0,
 31,
 65,
 44,
 103,
 49,
 4,
 31,
 31,
 52,
 29,
 65,
 44,
 31,
 15,
 0,
 66,
 43,
 53,
 20,
 23,
 31,
 92,
 25,
 3,
 13,
 3,
 3,
 107,
 15,
 43,
 23,
 53,
 55,
 1,
 3,
 2,
 161,
 15,
 50,
 0,
 74,
 40,
 44,
 69,
 27,
 2,
 31,
 3,
 65,
 65,
 44,
 3,
 124,
 31,
 66,
 31,
 53,
 3,
 53,
 53,
 43,
 29,
 53,
 22,
 45,
 31,
 43,
 0,
 37,
 3,
 53,
 130,
 3,
 1,
 3,
 64,
 16,
 31,
 161,
 44,
 65,
 31,
 0,
 58,
 87,
 19,
 69,
 31,
 3,
 44,
 0,
 31,
 31,
 50,
 112,
 67,
 48,
 5,
 1,
 3,
 5,
 87,
 0,
 122,
 29,
 4,
 63,
 31,
 19,
 0,
 0,
 3,
 82,
 155,
 53,
 58,
 6,
 37,
 38,
 52,
 53,
 53,
 34,
 44,
 18,
 43,
 65,
 53,
 5,
 65,
 29,
 5,
 124,
 3,
 4,
 13,
 31,
 48,
 44,
 16,
 101,
 65,
 70,
 31,
 44,
 3,
 31,
 50,
 22,
 154,
 5,
 53,
 131,
 0,
 53,
 38,
 3,
 44,
 65,
 31,
 68,
 3,
 31,
 111,
 29,
 58,
 31,
 100,
 52,
 7,
 20,
 124,
 4,
 11,
 68,
 3,
 22,
 0,
 31,
 31,
 3,
 53,
 53,
 10,
 66,
 52,
 50,
 120,
 0,
 44,
 58,
 65,
 11,
 19,
 29,
 39,
 3,
 178,
 5,
 180,
 59,
 31,
 31,
 0,
 5,
 23,
 0,
 31,
 29,
 76,
 80,
 53,
 28,
 65,
 44,
 10,
 53,
 3,
 44,
 6,
 29,
 53,
 3,
 79,
 11,
 0,
 13,
 0,
 7,
 18,
 88,
 53,
 70,
 31,
 0,
 85,
 53,
 31,
 31,
 11,
 104,
 0,
 53,
 0,
 55,
 31,
 92,
 66,
 53,
 55,
 3,
 2,
 100,
 0,
 10,
 29,
 53,
 69,
 20,
 95,
 31,
 29,
 99,
 13,
 66,
 0,
 10,
 0,
 43,
 3,
 37,
 29,
 39,
 1,
 104,
 43,
 32,
 14,
 29,
 57,
 183,
 30,
 75,
 3,
 31,
 42,
 53,
 99,
 0,
 0,
 20,
 83,
 47,
 23,
 53,
 65,
 42,
 2,
 17,
 0,
 44,
 42,
 53,
 67,
 71,
 0,
 29,
 5,
 43,
 57,
 18,
 0,
 31,
 43,
 86,
 0,
 31,
 124,
 43,
 3,
 0,
 18,
 53,
 0,
 0,
 25,
 0,
 130,
 65,
 58,
 33,
 46,
 58,
 0,
 70,
 3,
 50,
 90,
 31,
 43,
 35,
 53,
 65,
 89,
 31,
 43,
 71,
 16,
 31,
 66,
 31,
 3,
 145,
 23,
 23,
 38,
 19,
 44,
 31,
 108,
 31,
 86]

In [17]:
df_final=df_final.copy()
df_final['连0数']=list_0
df_final=df_final.T

df_final

,0,1,2,3,4,5,6,7,8,9,...,392,393,394,395,396,397,398,399,400,401
相关系数,0.478414,0.807008,0.935552,0.53185,0.946807,0.467851,0.654184,0.492129,0.465123,0.580837,...,0.186613,0.400608,0.904723,0.456592,0.919354,0.619759,0.685703,0.391804,0.630757,0.314835
变异系数,0.230465,0.282961,0.0899808,0.208272,0.0812637,0.306599,0.0661012,0.386446,0.268507,0.28181,...,1,0.32815,0.201469,0.223738,0.122992,0.289188,0.201834,0.432518,0.223997,0.596391
波动率,0.166667,0.0298507,0.449871,0.125,0.610156,0,0.323973,0,0,0.0333333,...,0,0,0.120924,0.25,1,0,0.2,0,0.125,0
总和_new,74.24,455,18247.2,96.97,11520,41.67,11580,56.94,46.97,257.58,...,50,240,126405,63.33,78.79,56.94,98.48,80.3,101.52,53.03
均值_new,2.9696,6.40845,95.5352,2.93848,107.664,3.20538,48.25,3.796,2.47211,8.04937,...,50,24,1708.18,2.5332,1.51519,3.55875,3.28267,6.17692,3.50069,6.62875
零值率,215,169,49,207,133,227,0,225,221,208,...,239,230,166,215,188,224,210,227,211,232
连0数,43,28,5,48,74,44,0,65,53,69,...,145,23,23,38,19,44,31,108,31,86

In [18]:
df_final.T

         相关系数       变异系数        波动率   总和_new   均值_new  零值率  连0数
0    0.478414   0.230465   0.166667    74.24   2.9696  215   43
1    0.807008   0.282961  0.0298507      455  6.40845  169   28
2    0.935552  0.0899808   0.449871  18247.2  95.5352   49    5
3     0.53185   0.208272      0.125    96.97  2.93848  207   48
4    0.946807  0.0812637   0.610156    11520  107.664  133   74
..        ...        ...        ...      ...      ...  ...  ...
397  0.619759   0.289188          0    56.94  3.55875  224   44
398  0.685703   0.201834        0.2    98.48  3.28267  210   31
399  0.391804   0.432518          0     80.3  6.17692  227  108
400  0.630757   0.223997      0.125   101.52  3.50069  211   31
401  0.314835   0.596391          0    53.03  6.62875  232   86

[402 rows x 7 columns]

In [19]:
df_final1=df_final.T

df_final1["变异系数"]=1-df_final1["变异系数"]
df_final1["波动率"]=1-df_final1["波动率"]
df_final1["总和_new"]=(df_final1["总和_new"]-38.89)/(591438.3)
df_final1["均值_new"]=df_final1["均值_new"]/28200
df_final1["零值率"]=1-df_final1["零值率"]/240
df_final1["连0数"]=e**(-0.1*(df_final1["连0数"]-5))


df_final1

,相关系数,变异系数,波动率,总和_new,均值_new,零值率,连0数
0,0.478414,0.769535,0.833333,5.97695e-05,0.000105305,0.104167,0.0223708
1,0.807008,0.717039,0.970149,0.000703556,0.00022725,0.295833,0.100259
2,0.935552,0.910019,0.550129,0.0307865,0.00338777,0.795833,1
3,0.53185,0.791728,0.875,9.82013e-05,0.000104202,0.1375,0.0135686
4,0.946807,0.918736,0.389844,0.0194122,0.00381786,0.445833,0.00100779
...,...,...,...,...,...,...,...
397,0.619759,0.710812,1,3.05188e-05,0.000126197,0.0666667,0.0202419
398,0.685703,0.798166,0.8,0.000100754,0.000116407,0.125,0.0742736
399,0.391804,0.567482,1,7.00158e-05,0.00021904,0.0541667,3.36331e-05
400,0.630757,0.776003,0.875,0.000105894,0.000124138,0.120833,0.0742736
401,0.314835,0.403609,1,2.39078e-05,0.000235062,0.0333333,0.000303539

In [20]:
df_final1.reset_index(drop=True, inplace=True)
A1=[0.18003228, 0.06824309*0.5, 0.06824309*0.5, 0.64105209*0.75, 0.64105209*0.25, 0.06824309*0.67, 0.11067253*0.33]
# [0.18003228 0.11067253 0.64105209 0.06824309]
# A1=[0.23230307,0.068862305,0.0688623505,0.4096642725,0.1365547575,0.05583552667,0.0279177633]

In [21]:
B = np.zeros((1, df_final1.shape[1]))
B

array([[0., 0., 0., 0., 0., 0., 0.]])

In [22]:
df_final1.shape[0]
df_final2=df_final1.T
df_final2.shape[1]
df_final2.shape[0]
df_final2

,0,1,2,3,4,5,6,7,8,9,...,392,393,394,395,396,397,398,399,400,401
相关系数,0.478414,0.807008,0.935552,0.53185,0.946807,0.467851,0.654184,0.492129,0.465123,0.580837,...,0.186613,0.400608,0.904723,0.456592,0.919354,0.619759,0.685703,0.391804,0.630757,0.314835
变异系数,0.769535,0.717039,0.910019,0.791728,0.918736,0.693401,0.933899,0.613554,0.731493,0.71819,...,-6.43929e-15,0.67185,0.798531,0.776262,0.877008,0.710812,0.798166,0.567482,0.776003,0.403609
波动率,0.833333,0.970149,0.550129,0.875,0.389844,1,0.676027,1,1,0.966667,...,1,1,0.879076,0.75,0,1,0.8,1,0.875,1
总和_new,5.97695e-05,0.000703556,0.0307865,9.82013e-05,0.0194122,4.70041e-06,0.0195136,3.05188e-05,1.36616e-05,0.00036976,...,1.87847e-05,0.000340035,0.213659,4.1323e-05,6.74627e-05,3.05188e-05,0.000100754,7.00158e-05,0.000105894,2.39078e-05
均值_new,0.000105305,0.00022725,0.00338777,0.000104202,0.00381786,0.000113666,0.00171099,0.00013461,8.76633e-05,0.000285439,...,0.00177305,0.000851064,0.0605736,8.98298e-05,5.37302e-05,0.000126197,0.000116407,0.00021904,0.000124138,0.000235062
零值率,0.104167,0.295833,0.795833,0.1375,0.445833,0.0541667,1,0.0625,0.0791667,0.133333,...,0.00416667,0.0416667,0.308333,0.104167,0.216667,0.0666667,0.125,0.0541667,0.120833,0.0333333
连0数,0.0223708,0.100259,1,0.0135686,0.00100779,0.0202419,1.64872,0.00247875,0.00822975,0.00166156,...,8.31529e-07,0.165299,0.165299,0.0368832,0.246597,0.0202419,0.0742736,3.36331e-05,0.0742736,0.000303539

In [23]:
row=3
column=5
min(A1[row-1], df_final2[row][column])
list=[]
list.append(min(A1[row-1], df_final2[row][column]))
list

[0.034121545]

In [24]:
df_final2

,0,1,2,3,4,5,6,7,8,9,...,392,393,394,395,396,397,398,399,400,401
相关系数,0.478414,0.807008,0.935552,0.53185,0.946807,0.467851,0.654184,0.492129,0.465123,0.580837,...,0.186613,0.400608,0.904723,0.456592,0.919354,0.619759,0.685703,0.391804,0.630757,0.314835
变异系数,0.769535,0.717039,0.910019,0.791728,0.918736,0.693401,0.933899,0.613554,0.731493,0.71819,...,-6.43929e-15,0.67185,0.798531,0.776262,0.877008,0.710812,0.798166,0.567482,0.776003,0.403609
波动率,0.833333,0.970149,0.550129,0.875,0.389844,1,0.676027,1,1,0.966667,...,1,1,0.879076,0.75,0,1,0.8,1,0.875,1
总和_new,5.97695e-05,0.000703556,0.0307865,9.82013e-05,0.0194122,4.70041e-06,0.0195136,3.05188e-05,1.36616e-05,0.00036976,...,1.87847e-05,0.000340035,0.213659,4.1323e-05,6.74627e-05,3.05188e-05,0.000100754,7.00158e-05,0.000105894,2.39078e-05
均值_new,0.000105305,0.00022725,0.00338777,0.000104202,0.00381786,0.000113666,0.00171099,0.00013461,8.76633e-05,0.000285439,...,0.00177305,0.000851064,0.0605736,8.98298e-05,5.37302e-05,0.000126197,0.000116407,0.00021904,0.000124138,0.000235062
零值率,0.104167,0.295833,0.795833,0.1375,0.445833,0.0541667,1,0.0625,0.0791667,0.133333,...,0.00416667,0.0416667,0.308333,0.104167,0.216667,0.0666667,0.125,0.0541667,0.120833,0.0333333
连0数,0.0223708,0.100259,1,0.0135686,0.00100779,0.0202419,1.64872,0.00247875,0.00822975,0.00166156,...,8.31529e-07,0.165299,0.165299,0.0368832,0.246597,0.0202419,0.0742736,3.36331e-05,0.0742736,0.000303539

In [25]:
# df_final2=df_final2.T
# df_final2['连0数'] = [1 if i >1 else i for i in df_final2['连0数']]
# df_final2=df_final2.T
# df_final2

In [26]:
max(list)

0.034121545

In [27]:
def mymin(list):
    for index in range(1, len(list)):
        if index == 1:
            temp = min(1, list[0]+list[1])
        else:
            temp = min(1, temp+list[index])
    return temp

In [28]:
list_final=[]
for column in range(0,df_final2.shape[1]):#column 402 row 7
        list = []
        for row in range(0, df_final2.shape[0]):
            list.append(A1[row]*df_final2[column][row])
        list_final.append(mymin(list))
list_final

[0.14644773173459782,
 0.22041970102469238,
 0.3065065554671281,
 0.1594677697872997,
 0.24547329794210795,
 0.14524619117204074,
 0.28830089611330684,
 0.14664052483514278,
 0.14675926445407958,
 0.16843992854334058,
 0.21755288267424894,
 0.12946361728125494,
 0.20927151799365257,
 0.1994983777521731,
 0.14649976693390207,
 0.21929463273114846,
 0.17118984745025317,
 0.17725997119531953,
 0.13392762787483745,
 0.1680862306699136,
 0.20840356789125009,
 0.1456528923546918,
 0.2644389058388775,
 0.19706984587043538,
 0.2801168027798533,
 0.22280014857339428,
 0.20599489978100552,
 0.18247016123834167,
 0.16524488829887282,
 0.23856997327150303,
 0.3774951781428336,
 0.18559030079889385,
 0.23127455659505572,
 0.13313467481724914,
 0.2071452380029045,
 0.234965681512844,
 0.34106226371292486,
 0.15415358954562616,
 0.20691977836252676,
 0.3611034668515835,
 0.18192350230676715,
 0.1784805219578045,
 0.15272596475540942,
 0.22364034359477175,
 0.14048767552183658,
 0.24596287315543733,
 0.16023470907065065,
 0.18941549263766097,
 0.18005996294150292,
 0.2351038015496804,
 0.14288771764220995,
 0.1906961675493878,
 0.24373144090462973,
 0.24863903455928102,
 0.3349296513020295,
 0.1715658633767846,
 0.1706302803289986,
 0.1496359814275606,
 0.15626260932939126,
 0.18150556812399518,
 0.1785491370258996,
 0.14774643167447465,
 0.15444597589736772,
 0.2790842893772329,
 0.2339887870481575,
 0.28178467084508363,
 0.2781718970283278,
 0.1424779493706206,
 0.22309764720693626,
 0.21136516238261477,
 0.14458207260644126,
 0.17320023166304876,
 0.2139143286983737,
 0.30203196950194083,
 0.29476664017390597,
 0.26734231908482553,
 0.13094245039107735,
 0.2667936291655518,
 0.18130572965683264,
 0.3311908549509994,
 0.2129569377489332,
 0.16879894669096376,
 0.17514370147722721,
 0.15063036767787577,
 0.1760947253872237,
 0.32702610606056726,
 0.21302063243614575,
 0.2745632090527737,
 0.1948515401215824,
 0.20838993790217603,
 0.19324595792009913,
 0.2860007721220782,
 0.1375455795904879,
 0.18410193405879335,
 0.1344438068204628,
 0.18203330893928144,
 0.15833207271261562,
 0.2799814726986511,
 0.19576013738759532,
 0.1383854032102166,
 0.1603065788551941,
 0.2193832216073757,
 0.14255925556915666,
 0.169279009496403,
 0.17988273487032766,
 0.23926083612503107,
 0.17851077942238605,
 0.637126807601464,
 0.16320617757495978,
 0.2637299946455196,
 0.17298857282311067,
 0.1479156651120948,
 0.29101624810245125,
 0.33283708875585727,
 0.26886228261095807,
 0.20405389326130052,
 0.21313243499126386,
 0.16406246459526422,
 0.12606454997645536,
 0.18748414337549915,
 0.18249763429488092,
 0.21045138106824385,
 0.2860760963193745,
 0.1819390647024065,
 0.1538298010657018,
 0.30093551187472584,
 0.17375494304838046,
 0.21875539701898047,
 0.2909075327575429,
 0.15409301514039797,
 0.500556086894914,
 0.19536969168198098,
 0.2293292179939517,
 0.16475533042238405,
 0.1375691958131801,
 0.17613002289501642,
 0.13657671078988776,
 0.26911185840936885,
 0.5092261879098343,
 0.6952421910680098,
 0.2790523576455435,
 0.15545972663186686,
 0.44254166094538383,
 0.1130682628292903,
 0.16778149000837225,
 0.24378656883923625,
 0.1585529859549371,
 0.1636823156126161,
 0.2419011707276017,
 0.31174887776320415,
 0.5615013576993411,
 0.2804326741762795,
 0.1165684914957921,
 0.2285455904073328,
 0.1598118625490981,
 0.16207175517340097,
 0.25448577779799997,
 0.16615073116563855,
 0.20050700534564686,
 0.14791755154076752,
 0.1455125325648077,
 0.12478765513589744,
 0.19825335037224445,
 0.1540709822690795,
 0.20274460450638607,
 0.15622403202590587,
 0.17375786304891935,
 0.14795953292370445,
 0.2810726784379422,
 0.19754486122450307,
 0.18461130603310674,
 0.26737172996447883,
 0.15582066607380296,
 0.29335588964515846,
 0.28783752459566103,
 0.18584439538559636,
 0.15474186112294633,
 0.24349706408068272,
 0.1320458966412606,
 0.21723573844217717,
 0.15294060786006963,
 0.19290600530512295,
 0.12423373543935656,
 0.18606087088706363,
 0.16108436814203128,
 0.2824052684111091,
 0.1632084128417668,
 0.23204494864086753,
 0.25491459319941207,
 0.11697554716353643,
 0.2610131418616206,
 0.14030811147388644,
 0.2265937433353416,
 0.4456060644944216,
 0.17106392179518104,
 0.17617065136347967,
 0.2860755439721784,
 0.15453770419048504,
 0.19686310017986672,
 0.16956589637786973,
 0.32318108287517244,
 0.28802103672270724,
 0.2284389650958673,
 0.13128735170263353,
 0.17533948857734094,
 0.2334804335186209,
 0.18356779381910898,
 0.23180339765601995,
 0.1871247629163676,
 0.2679893902611159,
 0.2269830340055108,
 0.1299308531486246,
 0.2684740535034465,
 0.17790109769245047,
 0.12976838737000912,
 0.27606757866811293,
 0.1940705736403272,
 0.33610491536366194,
 0.20173851430880216,
 0.17863948103591865,
 0.2900113019709906,
 0.1649097713119841,
 0.17952229215641652,
 0.2345055367764624,
 0.22720282451458584,
 0.1982820016958394,
 0.21614031695575436,
 0.14547986256067677,
 0.826083959634199,
 0.20740331870627107,
 0.13489664552251523,
 0.20270342939298067,
 0.22994808655815044,
 0.14812419832151774,
 0.22171553444757686,
 0.20478793858530092,
 0.29278654081070654,
 0.08561317182209832,
 0.2863376020441592,
 0.10775686678557383,
 0.13970320270412856,
 0.17849192162238464,
 0.16202909482567074,
 0.3336587892626237,
 0.25811599042222966,
 0.1490428392183399,
 0.3932746060459733,
 0.16248469673805455,
 0.18737230392174942,
 0.20194108779805514,
 0.1118948725093988,
 0.1723039599508086,
 0.24495626093050796,
 0.1975077405775426,
 0.18745628466894224,
 0.2625432170223882,
 0.14713432453727188,
 0.2787730066066299,
 0.1913377591783199,
 0.24345493905170362,
 0.17995194908066792,
 0.1375918000300958,
 0.27914500731329794,
 0.1658306415863879,
 0.2359022343535884,
 0.2509090697526347,
 0.2242893756034035,
 0.4812855972337135,
 0.24194065115878027,
 0.2475789280296056,
 0.22144862510403007,
 0.2170262024110596,
 0.2528263538467467,
 0.20591331055963863,
 0.5515749611004818,
 0.14889056229276373,
 0.13013339743462302,
 0.16253990029006016,
 0.21673840539081746,
 0.21722786354045287,
 0.1482883198329633,
 0.5673578298148818,
 0.14208379237829388,
 0.3994887301033616,
 0.12981221732808657,
 0.21810137194419285,
 0.1021868259061155,
 0.1712515639701732,
 0.14666740954414248,
 0.1440640747807448,
 0.3217268589815982,
 0.2781085127502231,
 0.09575692089243008,
 0.33015851159821874,
 0.19465637091271157,
 0.2078836701394701,
 0.1340160326845404,
 0.21441523245104027,
 0.14343573214466485,
 0.2079413342234945,
 0.221749125209718,
 0.15037324191635873,
 0.19833163501278822,
 0.24152678821716642,
 0.22087325012953127,
 0.48004140814249524,
 0.3918648864225445,
 0.508178495155955,
 0.20757995206824525,
 0.2836417915699086,
 0.16997007857149082,
 0.19351493365125902,
 0.19406159710078202,
 0.31110914181524213,
 0.1778687173142569,
 0.20598162253589358,
 0.14530635378671622,
 0.25533262784021277,
 0.17651615870715154,
 0.16079093151260346,
 0.11933899356375856,
 0.18058095598510296,
 0.1745643161928138,
 0.28983141961711256,
 0.18194076494409048,
 0.18202623801154127,
 0.197269246607384,
 0.1071401274326156,
 0.5515622969072791,
 0.5099561866809343,
 0.21314134334890264,
 0.2287591385959043,
 0.21089461539469576,
 0.13396784161539224,
 0.1603727355378246,
 0.20670059937549765,
 0.21645883677432254,
 0.35961966998403916,
 0.17823315255955108,
 0.5512852086094149,
 0.17873344172334227,
 0.2426835748404344,
 0.12907555816077007,
 0.1271628741174913,
 0.1708666657993392,
 0.3284519270441286,
 0.17508393642217232,
 0.42118623180308984,
 0.20816897556148226,
 0.14621895030821747,
 0.2348208354452602,
 0.4472055635643155,
 0.22547828244670146,
 0.16343079822332568,
 0.13702955794219737,
 0.4812918111851469,
 0.22839303292063928,
 0.19914537191540266,
 0.20905412743569216,
 0.271585635133454,
 0.7117032800486178,
 0.2570919648877587,
 0.173643261618134,
 0.35793365105673264,
 0.36904281513887877,
 0.19987137116382375,
 0.35736255684195034,
 0.17404227207679768,
 0.16297942715169958,
 0.18475311511598863,
 0.16578215804778534,
 0.1484788085727865,
 0.14119187752168894,
 0.3809808077654622,
 0.12302165353500263,
 0.27327514279056664,
 0.19132189507379566,
 0.17048613514314817,
 0.24200639693217746,
 0.1821860605028701,
 0.22953848265765558,
 0.17325507777997853,
 0.2219186357638815,
 0.17234534476646327,
 0.15650074628930136,
 0.22079394658061052,
 0.12578728824146898,
 0.2504029940071195,
 0.20580939429158995,
 0.14682451363426452,
 0.16565376153015862,
 0.28651408707782783,
 0.06820164133690977,
 0.13741049046207993,
 0.352689445794858,
 0.14042376611336396,
 0.21439209965909883,
 0.17377454876612655,
 0.1864756898376692,
 0.1265688839953622,
 0.17819968262799216,
 0.10615804168819266]

In [29]:
df_score1=pd.DataFrame(list_final)
df_score1=df_score1.reset_index()
df_score1

     index         0
0        0  0.146448
1        1  0.220420
2        2  0.306507
3        3  0.159468
4        4  0.245473
..     ...       ...
397    397  0.173775
398    398  0.186476
399    399  0.126569
400    400  0.178200
401    401  0.106158

[402 rows x 2 columns]

In [30]:
df_score1[0][390]

0.16565376153015862

In [31]:
df_score1=df_score1.sort_values(by=0, ascending=False)
#df_score1.to_excel("score1.xlsx")
df_score1=df_score1.reset_index(drop=True)
df_score1

     index         0
0      228  0.826084
1      360  0.711703
2      139  0.695242
3      107  0.637127
4      281  0.567358
..     ...       ...
397    401  0.106158
398    286  0.102187
399    292  0.095757
400    237  0.085613
401    392  0.068202

[402 rows x 2 columns]

In [32]:
#df_score1.to_excel("df_score_final.xlsx")

In [33]:
df_final2[1][2]

0.9701492537313433

In [34]:
df_final2

,0,1,2,3,4,5,6,7,8,9,...,392,393,394,395,396,397,398,399,400,401
相关系数,0.478414,0.807008,0.935552,0.53185,0.946807,0.467851,0.654184,0.492129,0.465123,0.580837,...,0.186613,0.400608,0.904723,0.456592,0.919354,0.619759,0.685703,0.391804,0.630757,0.314835
变异系数,0.769535,0.717039,0.910019,0.791728,0.918736,0.693401,0.933899,0.613554,0.731493,0.71819,...,-6.43929e-15,0.67185,0.798531,0.776262,0.877008,0.710812,0.798166,0.567482,0.776003,0.403609
波动率,0.833333,0.970149,0.550129,0.875,0.389844,1,0.676027,1,1,0.966667,...,1,1,0.879076,0.75,0,1,0.8,1,0.875,1
总和_new,5.97695e-05,0.000703556,0.0307865,9.82013e-05,0.0194122,4.70041e-06,0.0195136,3.05188e-05,1.36616e-05,0.00036976,...,1.87847e-05,0.000340035,0.213659,4.1323e-05,6.74627e-05,3.05188e-05,0.000100754,7.00158e-05,0.000105894,2.39078e-05
均值_new,0.000105305,0.00022725,0.00338777,0.000104202,0.00381786,0.000113666,0.00171099,0.00013461,8.76633e-05,0.000285439,...,0.00177305,0.000851064,0.0605736,8.98298e-05,5.37302e-05,0.000126197,0.000116407,0.00021904,0.000124138,0.000235062
零值率,0.104167,0.295833,0.795833,0.1375,0.445833,0.0541667,1,0.0625,0.0791667,0.133333,...,0.00416667,0.0416667,0.308333,0.104167,0.216667,0.0666667,0.125,0.0541667,0.120833,0.0333333
连0数,0.0223708,0.100259,1,0.0135686,0.00100779,0.0202419,1.64872,0.00247875,0.00822975,0.00166156,...,8.31529e-07,0.165299,0.165299,0.0368832,0.246597,0.0202419,0.0742736,3.36331e-05,0.0742736,0.000303539

In [35]:
df2_new['score']=list_final
df2_new['材料分类']=df2_new_abc['材料分类']
df2_new['供应商ID']=df2_new_abc['供应商ID']
df2_new=df2_new.sort_values(by='score', ascending=False)
df2_new

,W001,W002,W003,W004,W005,W006,W007,W008,W009,W010,...,均值,标准差,零值率,波动率,总和_new,均值_new,相关系数,score,材料分类,供应商ID
228,2006,1138,993,1027,1155,1175,1299,1786,1781,1570,...,1478.695833,1478.695833,0,0.421873,591478.33,2464.493042,0.956497,0.826084,A,S229
360,910,1212,1253,913,1181,838,1130,886,832,1400,...,1367.000000,1367.000000,0,0.390348,455666.67,1898.611125,0.946022,0.711703,C,S361
139,10,0,0,0,15687,4,1,11,6,3,...,1258.529167,1258.529167,21,0.000610529,457646.97,2089.712192,0.913604,0.695242,B,S140
107,556,7871,832,636,761,707,615,636,736,730,...,1003.958333,1003.958333,0,0.0352437,365075.76,1521.149000,0.896775,0.637127,B,S108
281,2,162,116,108,139,237,367,470,478,523,...,705.583333,705.583333,0,0.604936,282233.33,1175.972208,0.993949,0.567358,A,S282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,0,0,0,0,0,0,0,0,0,0,...,0.145833,0.145833,232,0,53.03,6.628750,0.314835,0.106158,B,S402
286,0,0,0,0,0,0,0,0,0,0,...,0.275000,0.275000,234,0,100.00,16.666667,0.291908,0.102187,B,S287
292,0,0,0,0,0,0,0,0,0,2,...,0.800000,0.800000,232,0,320.00,40.000000,0.313703,0.095757,A,S293
237,0,0,0,0,0,0,0,0,0,0,...,0.133333,0.133333,237,0,48.48,16.160000,0.222481,0.085613,B,S238
392,0,0,0,0,0,0,0,0,0,0,...,0.137500,0.137500,239,0,50.00,50.000000,0.186613,0.068202,B,S393

In [36]:
df2_new['材料分类'].values[50:100]

array(['C', 'C', 'A', 'B', 'A', 'B', 'B', 'B', 'C', 'A', 'B', 'B', 'B',
       'C', 'A', 'B', 'A', 'C', 'B', 'C', 'A', 'B', 'B', 'C', 'A', 'B',
       'B', 'B', 'B', 'B', 'A', 'C', 'C', 'B', 'C', 'A', 'C', 'C', 'B',
       'B', 'C', 'C', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'C'],
      dtype=object)

In [39]:
df2_new['供应商ID'].to_excel("df_score_index.xlsx",index_label=True)